---
- name: Install Packages
  hosts: vm
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for Docker's GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Ensure Docker's GPG key has the correct permissions
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository to APT sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list

    - name: Update Package Cache
      apt:
        update_cache: yes

    - name: Install Req. Packages with APT
      apt:
        name:
          - build-essential
          - fish
          - bat
          - firefox
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - grim
          - htop
          - jq
          - rsync
          - kitty
          - racket
          - ripgrep
          - eza
          - nodejs
        state: present

    - name: Install Req. Packages with SNAP
      community.general.snap:
        name:
          - discord
          - obsidian
          - spotify
          - nvim
          - telegram-desktop
          - jump
        classic: yes

    - name: Install Mise
      shell: curl https://mise.run | sh
      become: no

    - name: Install Starship
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y

    # - name: Install Doppler CLI
    #   shell: sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg && curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg && echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list && sudo apt-get update && sudo apt-get install doppler

    - name: Change Shell
      ansible.builtin.command: usermod --shell /usr/bin/fish {{ ansible_user }}
      become: yes

    - name: Clone Dotfiles
      git:
        repo: https://github.com/jaypyles/.dotfiles.git
        dest: ~/.dotfiles
      become: no

    - name: Copy Config
      shell: rsync -a ~/.dotfiles/.config/ ~/.config/
      become: no
